name = "yongcha"
main = "yongcha-worker.js"
compatibility_date = "2025-11-01"
account_id = "02709cbec18d848913b4246015b9148f"
workers_dev = false

[[routes]]
pattern = "yongcha.app/*"
zone_name = "yongcha.app"

[[kv_namespaces]]
binding = "DONWAY_ASSETS"
id = "7f0e90efaea64f3ab08ff00f8970b28b"
