name = "mbti-logistics"
main = "_worker.js"
compatibility_date = "2026-06-03"

routes = [
  { pattern = "donway.ai.kr/*", zone_name = "donway.ai.kr" },
  { pattern = "mbtico.kr/*", zone_name = "mbtico.kr" }
]
